// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHXJPk-jL8fqnY9QnaEDw3cI3_-degj3o',
    appId: '1:951908270541:web:eb36f2ceaefe8d5d26c484',
    messagingSenderId: '951908270541',
    projectId: 'shopatoz-6b5bd',
    authDomain: 'shopatoz-6b5bd.firebaseapp.com',
    storageBucket: 'shopatoz-6b5bd.firebasestorage.app',
    measurementId: 'G-CYKKH7K1RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72BB-JIrJQKaNzikO25JQ85GctWZGt4k',
    appId: '1:951908270541:android:28d308b805a82fa726c484',
    messagingSenderId: '951908270541',
    projectId: 'shopatoz-6b5bd',
    storageBucket: 'shopatoz-6b5bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJI1daKwPJD7f01qkisQ5i_oy6kBIHB8',
    appId: '1:951908270541:ios:3f5c81ca8cf998ee26c484',
    messagingSenderId: '951908270541',
    projectId: 'shopatoz-6b5bd',
    storageBucket: 'shopatoz-6b5bd.firebasestorage.app',
    iosBundleId: 'com.example.shopAToz',
  );
}
