import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shop_a_to_z_user/models/cart_model.dart';
import 'package:shop_a_to_z_user/models/order_model.dart';
import 'package:shop_a_to_z_user/models/rating_model.dart';
import '../models/app_user.dart';
import '../models/brand_model.dart';
import '../models/telescope_model.dart';

class DbHelper {
  //storing firebasefirestore instance in the "_db" - reference variable
  static final FirebaseFirestore _db = FirebaseFirestore.instance;
  //Collection name - be careful about it needs to matches with the firebase db collection name
  static const String collectionAdmin = 'Admins';
  //Brand Collection constants:
  static const String collectionBrand = 'Brands';
  //Telescope Collection Name
  static const String collectionTelescope = 'Telescopes';
  static const String collectionUser = 'Users';
  static const String collectionCart = 'MyCartItems';
  static const String collectionOrder = 'Orders';
  static const String collectionRating = 'Ratings';
  //Just check whether there is any document inside this admin collection, that matches user id(UID) [not necessary to access fields in it]
  static Future<bool> isAdmin(String uid) async {
    //returns the doc reference for the existing document inside the created 'admin collection'
    //next returns the doc snapshot(data)
    final snapshot = await _db.collection(collectionAdmin).doc(uid).get();
    //snapshot exists (doc exists - user is valid returns true orelse false (doc not exists, snapshot is empty)
    return snapshot.exists;
  }

//Add Brands
static Future<void> addBrand(BrandModel brand)  {
    final doc = _db.collection(collectionBrand).doc();
    brand.id = doc.id;
    return doc.set(brand.toJson());
}

//Get All Brands
static Stream<QuerySnapshot<Map<String, dynamic>>> getAllBrands() =>
    _db.collection(collectionBrand).snapshots();

//Add Telescope:
  static Future<void> addTelescope(TelescopeModel telescope) {
    final doc = _db.collection(collectionTelescope).doc();
    telescope.id =doc.id;
    return doc.set(telescope.toJson()); //toJson() automatically generated by freezed library
  }

//Get All Telescopes
  static Stream<QuerySnapshot<Map<String, dynamic>>> getAllTelescopes() =>
      _db.collection(collectionTelescope).snapshots();

// Update Telescope Field by telescope id
  static Future<void> updateTelescopeField(String id, Map<String, dynamic> map)  {
    return _db.collection(collectionTelescope).doc(id).update(map);
  }

  //<-----------------------------------User App----------------------------------------->
  //1) Add User
  static Future<void> addUser(AppUser appUser){
    return _db.collection(collectionUser)
        .doc(appUser.uid)
        .set(appUser.toJson());
  }

  //3)Add to cart
  static Future<void> addToCart(CartModel cartModel, String uid){
    return _db
        .collection(collectionUser)
        .doc(uid)
        .collection(collectionCart)
        .doc(cartModel.telescopeId)
        .set(cartModel.toJson());
  }

  //4)Remove from cart
  static Future<void> removeFromCart(String telescopeId, String uid){
    return _db
        .collection(collectionUser)
        .doc(uid)
        .collection(collectionCart)
        .doc(telescopeId)
        .delete();
  }

  //5) Get All Cart items:
  static Stream<QuerySnapshot<Map<String, dynamic>>> getAllCartItems(String uid) =>
      _db.collection(collectionUser)
          .doc(uid)
          .collection(collectionCart)
          .snapshots();


  //2) Does user exist based on that redirection will execute
  static Future<bool> doesUserExist(String userId) async {
    final snapshot = await _db.collection(collectionUser).doc(userId).get();
    return snapshot.exists;
  }

  //3) Update the cart quantity
  static Future<void> updateCartQty(String uid, CartModel model) {
    return _db.collection(collectionUser)
        .doc(uid)
        .collection(collectionCart)
        .doc(model.telescopeId)
        .set(model.toJson());
  }

  //4) Get User Information:
  //Whenever we call the collection --> returns 'query snapshot'
  //Whenever we call the document --> returns 'document snapshot'
  static Stream<DocumentSnapshot<Map<String, dynamic>>> getUserInfo(String uid) =>
      _db.collection(collectionUser).doc(uid).snapshots();

  //5) Save the orders
  static Future<void> saveOrder(OrderModel order) async {
   final wb = _db.batch();
   //1) Order Document
   final orderDoc = _db.collection(collectionOrder)
   .doc(order.orderId);
   wb.set(orderDoc, order.toJson());
   //2) Stock - telescope doc
   for(final cartModel in order.itemDetails){
     //Retrieve Map from this snapshot and use key and get the value
     final telescopeSnap = await _db.collection(collectionTelescope)
         .doc(cartModel.telescopeId)
         .get();
     //Stock update
     final prevStock = telescopeSnap.data()!['stock'];
     final telDoc = _db.collection(collectionTelescope)
     .doc(cartModel.telescopeId);
     wb.update(telDoc, {'stock' : prevStock - cartModel.quantity});
   }
   //3) User doc update
   //Save updated user document - to retrieve the user address to avoid entering details again and again
    final userDoc = _db.collection(collectionUser)
   .doc(order.appUser.uid);
   wb.set(userDoc, order.appUser.toJson());
   //4)commit all actions
    return wb.commit();
  }

  //6) Clear the cart items
  static Future<void> clearCart(String uid, List<CartModel> cartList){
    //Write Batch Object
    final wb = _db.batch();
    for(final model in cartList){
      //No of doc set to the 'write batch' in a loop, after finishing that batch will deleted (to clear all docs)
      final doc = _db.collection(collectionUser)
          .doc(uid)
          .collection(collectionCart)
          .doc(model.telescopeId);
      wb.delete(doc);
    }
    //This below command helps to execute all delete(any methods defined) are being set to the wb object
    //Any operation fails whole operation will get fails
    return wb.commit();
  }

  //Add Rating to telescopeProduct by user
  static Future<void> addRating(String telescopeId, RatingModel ratingModel) {
    return _db.collection(collectionTelescope)
        .doc(telescopeId)
        .collection(collectionRating)
        .doc(ratingModel.appUser.uid)
        .set(ratingModel.toJson());
  }

  //Get All Ratings of telescopeId
  // static Stream<QuerySnapshot<Map<String, dynamic>>> getAllRatings(String telescopeId) =>
  static Future<QuerySnapshot<Map<String, dynamic>>> getAllRatings(String telescopeId) =>
      _db.collection(collectionTelescope)
      .doc(telescopeId)
      .collection(collectionRating)
     // .snapshots();
      .get();
}