import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shop_a_to_z/models/brand_model.dart';
import 'package:shop_a_to_z/models/telescope_model.dart';
import '../utils/constants.dart';

class DbHelper {
  //storing firebasefirestore instance in the "_db" - reference variable
  static final FirebaseFirestore _db = FirebaseFirestore.instance;
  //Collection name - be careful about it needs to matches with the firebase db collection name
  static const String collectionAdmin = 'Admins';
  //Brand Collection constants:
  static const String collectionBrand = 'Brands';
  //Telescope Collection Name
  static const String collectionTelescope = 'Telescopes';
  static const String collectionOrder = 'Orders';
  static const String collectionUser = 'Users';
  //Just check whether there is any document inside this admin collection, that matches user id(UID) [not necessary to access fields in it]
  static Future<bool> isAdmin(String uid) async {
    //returns the doc reference for the existing document inside the created 'admin collection'
    //next returns the doc snapshot(data)
    final snapshot = await _db.collection(collectionAdmin).doc(uid).get();
    //snapshot exists (doc exists - user is valid returns true orelse false (doc not exists, snapshot is empty)
    return snapshot.exists;
  }

//Add Brands
static Future<void> addBrand(BrandModel brand)  {
    final doc = _db.collection(collectionBrand).doc();
    brand.id = doc.id;
    return doc.set(brand.toJson());
}

//Get All Brands
static Stream<QuerySnapshot<Map<String, dynamic>>> getAllBrands() =>
    _db.collection(collectionBrand).snapshots();

//Add Telescope:
  static Future<void> addTelescope(TelescopeModel telescope) {
    final doc = _db.collection(collectionTelescope).doc();
    telescope.id =doc.id;
    return doc.set(telescope.toJson()); //toJson() automatically generated by freezed library
  }

//Get All Telescopes
  static Stream<QuerySnapshot<Map<String, dynamic>>> getAllTelescopes() =>
      _db.collection(collectionTelescope).snapshots();

// Update Telescope Field by telescope id
  static Future<void> updateTelescopeField(String id, Map<String, dynamic> map)  {
    return _db.collection(collectionTelescope).doc(id).update(map);
  }

  //Get All Orders
  static Stream<QuerySnapshot<Map<String, dynamic>>> getAllOrders() =>
      _db.collection(collectionOrder).snapshots();

  //Get All Users
  static Stream<QuerySnapshot<Map<String, dynamic>>> getAllUsers() =>
      _db.collection(collectionUser).snapshots();
}